# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Energy_Charge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Energy_Charge
  pod 'Alamofire'  
  pod 'SwiftyJSON'

  target 'Energy_ChargeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Energy_ChargeUITests' do
    # Pods for testing
  end

end
